dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jx-slides
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: scala-akka-http-quickstart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
